# Default values for k8-golang-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  hostname: docker.io
  repository: /deepanshurawat6/botgauge-app
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  protocol: TCP
  port: 6565
  httpPort: 8080
  name: grpc
ingress:
  name: http
  protocol: HTTP
  port: 80
  extension: svc.cluster.local
serviceAccount:
  create: true
