name: Deploy to EKS

on:
  workflow_run:
    workflows: ["ci-pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v4.0.0
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name botgauge-eks-cluster --region us-west-1

    - name: Helm tool installer
      uses: Azure/setup-helm@v4.2.0

    - name: Deploy with Helm
      run: |
        helm upgrade --install botgauge-app ./botgauge-app --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/botgauge-app,image.tag=latest