name: ci-pipeline

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - 
        name: Run linters
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.47.2 && golangci-lint run
  
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME}}/botgauge-app:${{ github.sha}}
     
      - 
        name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
            image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/botgauge-app:${{ github.sha}}